---
# Create namespace
apiVersion: v1
kind: Namespace
metadata: 
  name: code-server
  labels:  
    app: code
    environment: lab  # indicate dev/staging/prod
    team: individual  # identify the responsible team
  annotations:
    description: "Course workshop 03"

# Create configMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-config
  namespace: code-server
  labels:
    app: code
    name: code-config
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-144.126.242.197.nip.io
