# Create secret
# should be isolated and exclude in commit (git.ignore)
---
apiVersion: v1
kind: Secret
metadata:
  name: code-secret
  namespace: code-server
  labels:
    app: code
    name: code-secret
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ= # 'password' base64 encoded
  SUDO_PASSWORD: cGFzc3dvcmQ= # 'password' base64 encoded
