# Create and specify POD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      commit: bggdbpod
  template:
    metadata: 
      name: bggdbpod
      namespace: bggns
      labels:
        app: bgg
        commit: bggdbpod
    spec:
      containers:
      - name: bggdbpod-container
        image:  stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggdb-port
          containerPort: 3306

# Create service 
# - provides a stable, reliable way to access and communicate with application components (like db) 
#   regardless of how the underlying pods are deployed or scaled
# - service also create name in DNS
#   <service name>.<namespace>.svc.cluster.local
#   example : dov-svc.myns.svc.cluster.local:8080
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP # ClusterIP/NodePort/LoadBalancer
  selector: 
    app: bgg
    commit: bggdbpod
  ports:
  - port: 3306 # Port that the Service will expose to the outside world
    targetPort: bggdb-port # Port on the container that the traffic will be forwarded to