# Create secret
# should be isolated and exclude in commit (git.ignore)
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
  labels:
    app: minio
    name: minio-secret
type: Opaque
data:
  MINIO_ROOT_PASSWORD: bWluaW9zZWNyZXQ= # 'miniosecret' base64 encoded
